# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e3351226c3225edc45c67e5d48348babdd3b4eab85933b11a2755e3c7c913b100c9aa198e0353f537615c1aa58e807c45f921ab57f79e6f5061bc0a8b21163

test:
  secret_key_base: 46831ed82e265e3cf1767aaf98a6db3e85351907343cf829c71005310f3d374afa67049a435e0ea7e6ca0d707bbf75c3423af11afcb66edd3a6666c42d062623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
